<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Services\Portal;
use Illuminate\Http\Request;

class SoaController extends Controller
{
    public function __construct(private Portal $portal) {}

    public function index(Request $request)
    {
        [$profile, $photoUrl] = $this->profile($request, $this->portal);
        $soa = $this->portal->soaData((int) $profile->enrollment_id);

        $color = ['Fully Paid' => 'emerald', 'Partially Paid' => 'amber', 'Unpaid' => 'rose', 'No Assessment' => 'slate'][$soa['payStatus']] ?? 'slate';

        return view('soa', compact('profile', 'photoUrl', 'soa', 'color'));
    }

    public function print(Request $request)
    {
        [$profile] = $this->profile($request, $this->portal);

        // Render the EXACT official slip the Cashier issued (1-up), same as the
        // native student/soa_print.php.
        $res = $this->portal->officialSlipData((int) $profile->enrollment_id);
        if ($res['status'] === 'paid') {
            return redirect()->route('soa')->with('error', 'This Statement of Account has been fully paid — there is nothing outstanding to print.');
        }
        if ($res['status'] !== 'ok') {
            return redirect()->route('soa')->with('error', 'Your official Statement of Account has not been generated by the Cashier yet. Please check back later or visit the Cashier’s office.');
        }

        return view('print.soa', ['slip' => $res['slip']]);
    }
}
