<?php

declare(strict_types=1);

require_once __DIR__ . '/../includes/student_auth.php';
require_once __DIR__ . '/../includes/soa_service.php';
require_once __DIR__ . '/../includes/soa_slip.php';

require_student_login();
$db   = db();
$sess = current_student();

$enrollmentId = (int) $sess['enrollment_id'];
$sy           = student_active_sy($db);

// Find this student's assessment for the active SY.
$aStmt = $db->prepare('SELECT id FROM student_assessment WHERE enrollment_id = ? AND school_year_id = ? LIMIT 1');
$aStmt->bind_param('ii', $enrollmentId, $sy['id']);
$aStmt->execute();
$aRow = stmt_fetch_assoc($aStmt);

// Only print an SOA the CASHIER has generated — the portal never creates one.
$soaId = 0;
if ($aRow) {
    $assessmentId = (int) $aRow['id'];
    $r = $db->query('SELECT id FROM soa_master WHERE assessment_id = ' . $assessmentId . ' ORDER BY id DESC LIMIT 1');
    if ($r && ($row = $r->fetch_assoc())) {
        $soaId = (int) $row['id'];
    }
}

if ($soaId === 0) {
    flash_set('error', 'Your official Statement of Account has not been generated by the Cashier yet. Please check back later or visit the Cashier’s office.');
    redirect_to(app_url('student/soa.php'));
}

// A fully-paid SOA is no longer offered for printing.
$rr  = $db->query("SELECT IFNULL(SUM(ps.balance),0) rem FROM soa_details sd JOIN payment_schedule ps ON ps.id = sd.schedule_id WHERE sd.soa_id = $soaId");
$rem = $rr ? (float) ($rr->fetch_assoc()['rem'] ?? 0) : 0.0;
$bal = (float) ($db->query('SELECT balance FROM student_assessment WHERE id = ' . $assessmentId)->fetch_assoc()['balance'] ?? 0);
if ($rem <= 0.009 || $bal <= 0.009) {
    flash_set('error', 'This Statement of Account has been fully paid — there is nothing outstanding to print.');
    redirect_to(app_url('student/soa.php'));
}

// Render the exact official slip the cashier issued (one statement per page).
soa_render_print_page($db, [$soaId], '1up', app_url('student/soa.php'));
