<?php

declare(strict_types=1);

function entrance_exam_questions(): array
{
    return [
        [
            'id' => 1,
            'category' => 'English',
            'question' => 'Choose the correct synonym of "rapid".',
            'choices' => ['A' => 'Slow', 'B' => 'Fast', 'C' => 'Heavy', 'D' => 'Late'],
            'answer' => 'B',
        ],
        [
            'id' => 2,
            'category' => 'English',
            'question' => 'Which sentence uses correct subject-verb agreement?',
            'choices' => [
                'A' => 'The list of names are on the table.',
                'B' => 'The list of names is on the table.',
                'C' => 'The list of names were on the table.',
                'D' => 'The list of names be on the table.',
            ],
            'answer' => 'B',
        ],
        [
            'id' => 3,
            'category' => 'English',
            'question' => 'Identify the correct punctuation: "Lets go to the library".',
            'choices' => [
                'A' => 'Lets, go to the library.',
                'B' => 'Let\'s go to the library.',
                'C' => 'Lets go to the library?',
                'D' => 'Lets go to the library!',
            ],
            'answer' => 'B',
        ],
        [
            'id' => 4,
            'category' => 'English',
            'question' => 'What is the antonym of "generous"?',
            'choices' => ['A' => 'Kind', 'B' => 'Helpful', 'C' => 'Selfish', 'D' => 'Honest'],
            'answer' => 'C',
        ],
        [
            'id' => 5,
            'category' => 'English',
            'question' => 'Choose the correct spelling.',
            'choices' => ['A' => 'Definately', 'B' => 'Definitely', 'C' => 'Defanitely', 'D' => 'Defnately'],
            'answer' => 'B',
        ],
        [
            'id' => 6,
            'category' => 'Math',
            'question' => 'What is 15% of 200?',
            'choices' => ['A' => '25', 'B' => '30', 'C' => '35', 'D' => '40'],
            'answer' => 'B',
        ],
        [
            'id' => 7,
            'category' => 'Math',
            'question' => 'Solve: 7(3 + 2) = ?',
            'choices' => ['A' => '35', 'B' => '14', 'C' => '17', 'D' => '10'],
            'answer' => 'A',
        ],
        [
            'id' => 8,
            'category' => 'Math',
            'question' => 'If x + 9 = 21, what is x?',
            'choices' => ['A' => '10', 'B' => '11', 'C' => '12', 'D' => '13'],
            'answer' => 'C',
        ],
        [
            'id' => 9,
            'category' => 'Math',
            'question' => 'What is the value of 3^3?',
            'choices' => ['A' => '9', 'B' => '18', 'C' => '27', 'D' => '81'],
            'answer' => 'C',
        ],
        [
            'id' => 10,
            'category' => 'Math',
            'question' => 'Which fraction is equivalent to 0.75?',
            'choices' => ['A' => '1/2', 'B' => '2/3', 'C' => '3/4', 'D' => '4/5'],
            'answer' => 'C',
        ],
        [
            'id' => 11,
            'category' => 'Science',
            'question' => 'What is the basic unit of life?',
            'choices' => ['A' => 'Atom', 'B' => 'Cell', 'C' => 'Molecule', 'D' => 'Organ'],
            'answer' => 'B',
        ],
        [
            'id' => 12,
            'category' => 'Science',
            'question' => 'Which planet is known as the Red Planet?',
            'choices' => ['A' => 'Venus', 'B' => 'Mars', 'C' => 'Jupiter', 'D' => 'Mercury'],
            'answer' => 'B',
        ],
        [
            'id' => 13,
            'category' => 'Science',
            'question' => 'Water boils at what temperature at sea level?',
            'choices' => ['A' => '90 C', 'B' => '95 C', 'C' => '100 C', 'D' => '120 C'],
            'answer' => 'C',
        ],
        [
            'id' => 14,
            'category' => 'Science',
            'question' => 'What gas do plants absorb during photosynthesis?',
            'choices' => ['A' => 'Oxygen', 'B' => 'Nitrogen', 'C' => 'Carbon Dioxide', 'D' => 'Hydrogen'],
            'answer' => 'C',
        ],
        [
            'id' => 15,
            'category' => 'Science',
            'question' => 'Which organ pumps blood through the body?',
            'choices' => ['A' => 'Lungs', 'B' => 'Brain', 'C' => 'Heart', 'D' => 'Liver'],
            'answer' => 'C',
        ],
        [
            'id' => 16,
            'category' => 'Logic',
            'question' => 'If all roses are flowers and some flowers fade quickly, which is always true?',
            'choices' => [
                'A' => 'All roses fade quickly.',
                'B' => 'Some roses are not flowers.',
                'C' => 'All roses are flowers.',
                'D' => 'No flowers are roses.',
            ],
            'answer' => 'C',
        ],
        [
            'id' => 17,
            'category' => 'Logic',
            'question' => 'Find the next number: 2, 4, 8, 16, ?',
            'choices' => ['A' => '18', 'B' => '24', 'C' => '30', 'D' => '32'],
            'answer' => 'D',
        ],
        [
            'id' => 18,
            'category' => 'Logic',
            'question' => 'Which word does not belong: Triangle, Square, Circle, Sparrow?',
            'choices' => ['A' => 'Triangle', 'B' => 'Square', 'C' => 'Circle', 'D' => 'Sparrow'],
            'answer' => 'D',
        ],
        [
            'id' => 19,
            'category' => 'Logic',
            'question' => 'If BOOK is coded as CPPL, how is PEN coded using the same pattern?',
            'choices' => ['A' => 'QFO', 'B' => 'QEN', 'C' => 'PEO', 'D' => 'REN'],
            'answer' => 'A',
        ],
        [
            'id' => 20,
            'category' => 'Logic',
            'question' => 'A clock shows 3:00. What is the angle between the hands?',
            'choices' => ['A' => '45 degrees', 'B' => '90 degrees', 'C' => '120 degrees', 'D' => '180 degrees'],
            'answer' => 'B',
        ],
        [
            'id' => 21,
            'category' => 'General Knowledge',
            'question' => 'What does ICT stand for?',
            'choices' => [
                'A' => 'International Computer Technology',
                'B' => 'Information and Communication Technology',
                'C' => 'Integrated Communication Tools',
                'D' => 'Information Computer Training',
            ],
            'answer' => 'B',
        ],
        [
            'id' => 22,
            'category' => 'General Knowledge',
            'question' => 'Which of these is a renewable energy source?',
            'choices' => ['A' => 'Coal', 'B' => 'Diesel', 'C' => 'Solar', 'D' => 'Natural Gas'],
            'answer' => 'C',
        ],
        [
            'id' => 23,
            'category' => 'General Knowledge',
            'question' => 'Which branch of government interprets laws?',
            'choices' => ['A' => 'Executive', 'B' => 'Legislative', 'C' => 'Judicial', 'D' => 'Local'],
            'answer' => 'C',
        ],
        [
            'id' => 24,
            'category' => 'General Knowledge',
            'question' => 'What is the capital city of the Philippines?',
            'choices' => ['A' => 'Cebu', 'B' => 'Manila', 'C' => 'Davao', 'D' => 'Baguio'],
            'answer' => 'B',
        ],
        [
            'id' => 25,
            'category' => 'General Knowledge',
            'question' => 'Which value best supports academic integrity?',
            'choices' => ['A' => 'Dishonesty', 'B' => 'Plagiarism', 'C' => 'Responsibility', 'D' => 'Negligence'],
            'answer' => 'C',
        ],
    ];
}
